#!/bin/bash

echo "Compile your project here"
cd project/
$JAVA_HOME/bin/keytool -import -alias pebble -cacerts -noprompt -storepass changeit -file pebble.minica.pem
cd netsec-acme/
mvn clean package
ls -l target/lib
cd ../..