#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."
cd project/netsec-acme
java -cp target/lib/*;target/netsec-acme-0.0.1-SNAPSHOT.jar elianzuoni.netsec.acme.app.App
